circleCI fix and Folder Structure

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,7 +1,4 @@
 version: 2.1
-orbs:
-  slack: circleci/slack@4.12.5
-  aws-ecr: circleci/aws-ecr@8.2.1
 executors:
   docker-executor:
     docker:
@@ -9,13 +6,14 @@ executors:
         auth:
           username: $DOCKERHUB_USERNAME
           password: $DOCKERHUB_PASSWORD
+
 jobs:
   build_and_push_tag_image:
     executor: docker-executor
     environment:
-      JVM_OPS: -Xmx512m
+      JVM_OPTS: -Xmx512m
       TERM: dumb
-      GITHUB_TOKEN: ${GITHUB_TOKEN}
+      GITHUB_TOKEN: ${GITHUB_TOKEN}  # Add the GitHub token as an environment variable
 
     steps:
       - checkout
@@ -26,6 +24,7 @@ jobs:
           command: |
             # Set environment variables
             IMAGE_TAG=$CIRCLE_TAG
+
             # Check if the Docker image with the same tag already exists in Docker Hub
             if curl -s -f -u "$DOCKERHUB_USERNAME":"$DOCKERHUB_PASSWORD" "https://hub.docker.com/v2/repositories/fynarfin/ph-ee-ilp-service/tags/$IMAGE_TAG" > /dev/null; then
               echo "Skipping the build and push as the tag $IMAGE_TAG already exists in Docker Hub."
@@ -42,39 +41,40 @@ jobs:
 
           # when: always  # The job will be executed even if there's no match for the tag filter
 
-    build_and_push_latest_image:
-      executor: docker-executor
-      environment:
-        JVM_OPTS: -Xmx512m
-        TERM: dumb
+  build_and_push_latest_image:
+    executor: docker-executor
+    environment:
+      JVM_OPTS: -Xmx512m
+      TERM: dumb
 
-      steps:
-        - checkout
-        # Install Docker to build and push the image
-        - setup_remote_docker:
-            version: 20.10.14
+    steps:
+      - checkout
+      # Install Docker to build and push the image
+      - setup_remote_docker:
+          version: 20.10.14
 
-        # Build the Docker image
-        - run:
-            name: Build Docker image
-            command: |
-              ./gradlew checkstyleMain
-              ./gradlew bootJar
-              docker build -t fynarfin/ph-ee-ilp-service:latest .
-              if [ "$CIRCLE_BRANCH" != "develop" ]; then
-                PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
-                PR_TITLE=$(curl -sSL "https://api.github.com/repos/fynarfin/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
-                JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
-                if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
-                docker image tag fynarfin/$CIRCLE_PR_REPONAME:latest fynarfin/$CIRCLE_PR_REPONAME:$JIRA_STORY
-              fi
+      # Build the Docker image
+      - run:
+          name: Build Docker image
+          command: |
+            ./gradlew checkstyleMain
+            ./gradlew bootJar
+            docker build -t fynarfin/ph-ee-ilp-service:latest .
+            if [ "$CIRCLE_BRANCH" != "develop" ]; then
+              PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
+              PR_TITLE=$(curl -sSL "https://api.github.com/repos/fynarfin/$CIRCLE_PR_REPONAME/pulls/$PR_NUMBER" | jq -r '.title')
+              JIRA_STORY=$(echo $PR_TITLE | cut -d "[" -f2 | cut -d "]" -f1 | tr '[A-Z]' '[a-z]')
+              if [ -z "$JIRA_STORY" ]; then echo "Invalid PR title" && exit 1; else echo "Ticket NO: $JIRA_STORY"; fi
+              docker image tag fynarfin/$CIRCLE_PR_REPONAME:latest fynarfin/$CIRCLE_PR_REPONAME:$JIRA_STORY
+            fi
 
-        - run:
+      # Log in to DockerHub using environment variables
+      - run:
           name: Login to DockerHub
           command: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
 
-          # Push the Docker image to DockerHub
-        - run:
+      # Push the Docker image to DockerHub
+      - run:
           name: Push Docker image to DockerHub
           command: |
             if [ "$CIRCLE_BRANCH" = "develop" ]; then
@@ -100,4 +100,3 @@ workflows:
       - build_and_push_latest_image:
           context:
             - DOCKER
-
